language: node_js
node_js:
- 8.0.0

# Adicione a branch onde está a instalação do Hexo
branches:
  only:
  - master

before_install:
- npm install -g hexo

install:
- npm install

# Configure seu nome de usuário e e-mail
before_script:
- git config --global user.name 'Mario Souto'
- git config --global user.email 'soutomarios@gmail.com'


script:
- hexo generate

# Configure a Branch a ser feito o deploy
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Site updated'
- git branch -m master
- git push -q -u origin master
