# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

encoding: utf-8

# Site settings
title: Mario Souto
author: Mario Souto
sub-title: Desenvolvedor Front-End
email: mariosoutoskn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  "Meu Blog pessoal"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mariosouto.com" # the base hostname & protocol for your site
twitter_username: marioquemario
github_username:  mariosout

#minify settings
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  comments: all
  endings: []
  profile: false

# Navigation Menu
links:
  - title: Artigos
    url: /
  - title: Projetos
    url: /projetos
  - title: Sobre mim
    url: /sobre

# exclude
exclude: ['gulpfile.js','package.json', 'node_modules']
