version: 2.1
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
        environment: 
          repo_token: lMhmDbvzUYOq3UViwOsrorbULyFtr0byN 
    steps:
      - checkout
      - run: echo 'Running'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
