version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "93:e9:6f:ab:ad:4f:93:e6:65:64:3b:c5:4e:56:25:ef"
      - checkout
      # Setup git things
      - run: git config --global user.name 'Mario Souto'
      - run: git config --global user.email 'soutomarios@gmail.com'
      - run: npm install && ./node_modules/.bin/hexo generate
      # Deploy things
      - run: mkdir .deploy
      - run: cd .deploy && git clone --depth 1 --branch master --single-branch git@github.com:omariosouto/omariosouto.github.io.git
      - run: cd .deploy && rm -rf ./*
      - run: cd .deploy && echo 'Before copy' && ls -a
      - run: cd .deploy && cp -r ../public/* ./
      - run: cd .deploy && echo 'After copy' && (git init && git remote add -t master origin git@github.com:omariosouto/omariosouto.github.io.git)
      - run: cd .deploy && git status && git add -A .
      - run: cd .deploy && git commit -m 'Site updated'
      - run: cd .deploy && git branch -m master
      - run: cd .deploy && git push -q -u origin master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
general:
  branches:
    only:
     - develop