# Read More text
excerpt_link: Leia mais...

username:
  site    : omariosouto 
  twitter : omariosouto
  github  : omariosouto
  facebook: omariosouto
  linkedin: omariosouto
  medium  : omariosouto

description: Vivo no 220v, sempre atrás de um filme/rolê novo e codando desafios aleatórios em JavaScript. Adoro fazer sites e falar/dar aulas sobre isso na @caelum e @alura

menu:
  Home : /
  Sobre: /about
  Feed : /feed.xml
