menu:
  Home: /
  Feed: /feed.xml
  Sobre mim: /about

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: true
disqus_shortname: mariosouto

# google analytics
googleTrackId: UA-69548205-5
