menu:
  Home: /
  Archives: /archives
  About Me: /about

# duoshuo comment
duoshuo: false
duoshuo_name: 

# disqus comment
disqus: true
disqus_shortname: mariosouto

# google analytics
googleTrackId: 
